### ISSUE TITLE
Gerador de banner de pedido de doação

### ISSUE THREAD

**Issue by gustavorps** [ArgoCrew/hematopy#1]
**Requisitos**
- [x] Foto do paciente
- [x] Nome completo
- [x] Tipo sanguíneo
- [x] Local de doação
- [x] Comando em CLI que aceite o seguinte formato:
  `hematopy blood-donation new --name="João da Silva" --bloodType="AB+" --address="Hemoes, Av. Mal. Campos, 1468 - Nazareth, Vitória - ES" --template=request-for-blood-donation-facebook-v1 --output=./doacao-joao-facebook.png`

**Referência**
No diretório [/assets](https://github.com/ArgoCrew/hematopy/tree/master/assets) podem ser arquivos de referência, como: 

![Pedido de Doação de Sangue](https://raw.githubusercontent.com/ArgoCrew/hematopy/7febd19094ece4216dbb027d53bed4f9cc515a18/assets/request-for-blood-donation-facebook-v1.png)

**Comment by GustavoRPS** [comment]
Pull Request https://github.com/ArgoCrew/hematopy/pull/3 promete finalizar essa issue.

**Comment by GustavoRPS** [comment]
Pelo jeito a PL #3 finalizou a demandas dessa issue! :-]
