### ISSUE TITLE
Methods to search cities and states

### ISSUE THREAD

**Issue by mikaelhadler** [ArgoCrew/hematopy#23]
Hey, dude, I have a question. How should end load cities and states information?

I thought in three possibilities:
1. Mock to two files with all Brazilian states and cities (Not recommend)

2. Send a string to API what does the city or state contain?
     -> searchAddres (search)
         -> api / getAddress
             if contains state
                 return list of states with | match the string search
             else
                 return list of cities (city, state) with contains | match the string search

I thought to something similar to [Fuse] (https://github.com/krisk/Fuse).

So, how we keep going?

**Comment by mikaelhadler** [comment]
For not stop my work, i go use fake information with a default valeu, only for continue. :+1:

**Comment by GustavoRPS** [comment]
I think about using a service like Google Place API.

Here is a good example of an [web component using the autocomplete feature](https://www.webcomponents.org/element/paper-input-place#additional-properties)

I like the suggestion of implementing a fuzzy-search algorithm however my current mindset is to reduce the need for implementation to the maximum and reuse the maximum of existing solutions.

Many thanks for the proactivity in issues @mikaelhadler :-]

**Comment by mikaelhadler** [comment]
No problem @GustavoRPS :]

I have success with the [Google Place API with the feature autocomplete](https://www.webcomponents.org/element/paper-input-place#additional-properties). :+1: 

Now i just need to integrate form and create a PR.
